### ISSUE TITLE
dom.indexedDB.enabled breakes Youtube

### ISSUE THREAD

**Issue by M0r13n** [allo-/firefox-profilemaker#130]
I just had an issue with firefox and Youtube. It took me some time to figure out, why youtube kept crashing instantly. It turns out that disabling dom.indexedDB.enabled seems to make it impossible to view youtube videos.  I would recommend that we may add additonal information, so that others experiencing the same issue, can try it. 

I verified the issue with two machines. Disabling dom.indexedDB.enabled directly crashes Youtube.

**Comment by allo-** [comment]
I can reproduce it here in Waterfox 56, but not in Firefox 61.

The tab crash is a Firefox bug, because it should never crash even when a site breaks becaue of a setting. If you can reproduce with a supported build open a bug in https://bugzilla.mozilla.org/

For Waterfox, Palemoon and unsupported Firefox versions, this is a problem. I think waterfox and palemoon should try to fix it, FF 56 and 52esr (soon) are out of support.

**Comment by allo-** [comment]
As the setting already has a warning that it may break sites (in the sense of not working scripts), I think the issue should be closed as it is a browser bug, when a site crashes because of a switch of the browser.
What do you think?

**Comment by M0r13n** [comment]
I am fine with that. I just wanted to share my experience, because until now ( i am using FF 61) i never had any problem with that setting. But as you said, there is already a warning. So we can close it.

**Comment by allo-** [comment]
But the tab does crash for you? This is a firefox bug and 61 is a supported release. If you can reproduce, open a bug in their bugtracker, so they can fix it. Because it seems I can here even use youtube (to watch videos, no idea about other features) with indexedDB off, but you seem to have found a crash bug.

**Comment by M0r13n** [comment]
I can reproduce this issue: Crash-Link: https://crash-stats.mozilla.com/report/index/70c4fc37-1626-41c2-8926-bade40180827#tab-rawdump

i guess i am going to file a bug in their bugtracker. :-)

**Comment by allo-** [comment]
So this one is a Mozilla bug, see the attached bugzilla entries to your crash report as well.
But when you find sites which do not work without indexeddb (no crash, but broken scripts in the website), feel free to open another bug with "breaks sites" label.

I want to implement a "feature_breaks: ..." tag for settings anyway and this could for example include information about popular sites or description of features which will not work. IndexedDB already has such a label with regard to twitter, but many of the off-switches for html5-features are breaking some sites.

**Comment by jiaweihli** [comment]
`dom.indexedDB.enabled` also breaks gmail for me in ff 62 and ff 63 beta - took me a good 10 minutes to hunt this down.
worth creating another issue?

**Comment by allo-** [comment]
Yep. Let's track the issues about broken sites (not broken firefox) here: https://github.com/allo-/firefox-profilemaker/issues/135
