### ISSUE TITLE
Addons won't install on FF 62.0

### ISSUE THREAD

**Issue by boyd8444** [allo-/firefox-profilemaker#134]
Umatrix and uBlock origin xpi addons are not installed when bundled into the profile.zip file. The xpi files appear in the extensions folder, but disappear after firefox is launched and are not automatically installed.

**Comment by allo-** [comment]
Probably they are not installed, because they are no quantum firefox addons. I hoped they would be installed with a note "you need to update this addon for it to work again" and users could just update to the latest quantum/non-quantum version.

This means we can either support older versions (like palemoon, waterfox) or quantum firefox versions with the addons. see also https://github.com/allo-/firefox-profilemaker/issues/92

**Comment by allo-** [comment]
I updated all addons to the current addons.mozilla.org version and removed the incompatible ones.

**Comment by boyd8444** [comment]
Thanks, it seems to be working now. I appreciate all your effort!
