### ISSUE TITLE
Does the google-no-tracking-url addon still work?

### ISSUE THREAD

**Issue by adrian5** [allo-/firefox-profilemaker#140]
Looking at the more recent [reviews](https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/reviews/) of the addon, it would seem that it doesn't do its job anymore. Can anyone confirm this?

An alternative might be [Google search link fix](https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/), which has been updated more recently than the former.

**Comment by StarPicard** [comment]
I would recommend https://github.com/sblask/webextension-skip-redirect, wich supports more websites than just google.

**Comment by allo-** [comment]
Indeed, I had the problem that I tried different addons and quite a few seemed not to work correctly.
Currently I use https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/, but I will look into using the skip-redirect addon.

**Comment by allo-** [comment]
I am not sure, if the skip-redirect addon actually removes the google redirects. It seems to depend on links, which contain "something=https://someurl". The google results hide the tracking URL until you click and I am not sure if they match the format.

But this addon in addition to a working google redirects addon would still be a good idea. 

Side note: 
I kind of dislike their ``www.google.com/chrome/?or-maybe-rather-firefox=http%3A%2F%2Fwww.mozilla.org/`` example, as this is a false-positive URL for the addon.
Try clicking it without the addon, you will end up on the google chrome site and the addon would redirect you to mozilla. Such a false positive URL would need to be whitelisted instead of used for advertising the function of the addon.

**Comment by Atavic** [comment]
This addon removes both redirects and *utm* parameters. 

https://addons.mozilla.org/firefox/addon/neat-url/
https://github.com/Smile4ever/Neat-URL

**Comment by allo-** [comment]
@Atavic  Are you sure NeatURL actually removes google's transparent redirects?

**Comment by Atavic** [comment]
[Request Control](https://github.com/tumpio/requestcontrol) does it by deafult and can create it's own rules for stripping away utm parameters.

**Comment by Atavic** [comment]
[Request Control](https://github.com/tumpio/requestcontrol) does it by default and can also create its own rules for stripping away utm parameters.

**Comment by allo-** [comment]
Request Control looks very nice for this. It seems to match the concrete redirect URLs and has an easy to configure blacklist and the ``utm_`` filter which may get false positives is disabled by default.
I think this can be a good replacement which won't break anything.

Do you currently use it and it works fine for you?

**Comment by Atavic** [comment]
Yes, I actually use it.

**Comment by allo-** [comment]
What about https://addons.mozilla.org/de/firefox/addon/dont-track-me-google1/

**Comment by Atavic** [comment]
https://github.com/Rob--W/dont-track-me-google works only when you search in google search. Request Control has a broader scope.

**Comment by allo-** [comment]
I think about keeping this google-only with the most simple addon and adding another option for request control.
