### ISSUE TITLE
Bundle the profile with a firefox installer

### ISSUE THREAD

**Issue by elypter** [allo-/firefox-profilemaker#145]
It would make setting up a custom firefox a lot easier if the generated profile was bundled with a firefox installer. to avoid repacking the archive for every download something like this could be used https://github.com/Grandt/PHPZipMerge

**Comment by allo-** [comment]
I do not think I want to do this.
The extensions are already a small problem, because they are already outdated and possibly when you download the profile.zip.

Redistributing Firefox would need to have a mechanism to bundle the latest and then people still may consider in the future "let's use the old installer with privacy addons instead of a recent version". Furthermore I think Mozilla says you may not use their trademarks when redistributing changed versions of Firefox.

And I am currently not sure if you can ship both default config and default addons in the installation directory. Even when you do, the user may want to have two profiles, one with standard Firefox (e.g. to see which privacy settings break sites) and one with the generated profile.

So I think there are many argument against it in this project.  
But you can try to create an own project which can create such installers. If you do and need some kind of additional information which is not currently in the zip, I will see if I can help to provide a suitable output format which can be used with your program.
