### ISSUE TITLE
ffprofile.com : privacy.resistFingerprinting ?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [allo-/firefox-profilemaker#228]
Hi.
I do not find following:
privacy.resistFingerprinting
as suppposed
here in german:
https://www.kuketz-blog.de/firefox-aboutconfig-user-js-firefox-kompendium-teil10/
And there are more security options for Firefox.
What do you mean? :)

**Comment by allo-** [comment]
It's here: https://github.com/allo-/firefox-profilemaker/blob/master/settings/resist-fingerprinting.json

And in many cases you probably should not use it.
You get a lot of unwanted side effects, on the one hand broken websites and on the other hand other privacy options not working anymore, because they are replaced by the values set by the resistFingerprinting switch.
