### ISSUE TITLE
Non-working site... can't watch video...

### ISSUE THREAD

**Issue by ThEnchanted** [allo-/firefox-profilemaker#244]
Hello so after checking some sites that are commonly used and one of them is "broken"
can't play video, the video player used in there is Vimeo and no I can't find an uploader of this video

Theme on Mozilla: [https://support.mozilla.org/en-US/questions/1364987](url)

**Comment by allo-** [comment]
If an author sets a video to non-public this has nothing to do with your browser profile.

**Comment by allo-** [comment]
You liked a discussion about a video, that was made private by its owner. You were suggested to ask the owner to make it public. This has nothing to do with your browser profile at all.

**Comment by ThEnchanted** [comment]
Look here see it's only in specially this browser (made in ffprofile) video bellow look
p.s now it's high quality
link: https://youtu.be/lCPRa29DRBM

**Comment by allo-** [comment]
Please post either a deep-link to the video where I can test myself or at least the specific setting that breaks something.

There *are* many settings that can and will break things, that's why the generator gives a short description and allows to customize the settings instead of just providing a user.js file. For example uMatrix *will* require you to allow third-party scripts before videos are loading on many sites.

So "can't watch" is nothing that we can do something about as long as it's not clear what's the actual problem. The best you can do it to try to disable settings until it works again, so we know what's causing the problem.

By the way I don't know how you're formatting your urls, but in the text I get the url and the target is https://github.com/allo-/firefox-profilemaker/issues/url for some reason.

**Comment by ThEnchanted** [comment]
So I was viewing every link in HTML view and I found it, but the issue it's private... I could give you my login "privately" so you can check and test everything that needs to be done... what do you think?

**Comment by allo-** [comment]
So you can view the video with a fresh browser profile and your login? Or does it say private in any case?

I don't want to debug with your credentials. When it can only be accessed by you, try to find out which features are causing the problem and when it seems reasonable that they will break sites we can add a notice to the switch that it may break video playback.
