### ISSUE TITLE
Disable HTML5 Video Autoplay

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#46]
One for the Annoyances Category.

`media.autoplay.enabled`

**Comment by IDKwhattoputhere** [comment]
This option "breaks" YouTube. You have to click on the video progress bar and can't just press play. Is that expected? Otherwise this settings could be interesting too:

Disable HTML5 video autoplay until in foreground

Add an option to stop autoplay until the tab gains focus.
https://www.ghacks.net/2016/11/14/firefox-51-blocks-automatic-audio-playback-in-non-active-tabs/

Setting: media.block-autoplay-until-in-foreground: true
Title: Block autoplay of background tabs
Description: Disable Autoplay until a tab becomes active.

**Comment by allo-** [comment]
From the help text: "Per default, &lt;video&gt; tags are allowed to start automatically. Note: When disabling autoplay, you will have to click pause and play again on some video sites."

The article says that the new setting is on by default and in my profile it looks like it is.

Closing, because it works as intended. For more comfortable enable/disable autoplay you probably need some extension.
